apiVersion: v1
kind: Service
metadata:
  name: go-swagger
  namespace: test
  labels:
    app: go-swagger
spec:
  type : ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: go-swagger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-swagger
  name: go-swagger
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-swagger
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: go-swagger
    spec:
      containers:
      - name: go-swagger
        image: murugappans/goswaggertest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080